# Generated by Django 4.1.1 on 2022-09-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakestore', '0002_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
