# Generated by Django 4.1.1 on 2022-09-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestore', '0003_remove_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
