# Generated by Django 4.1.1 on 2022-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestore', '0006_alter_cart_total_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_ordering',
            field=models.IntegerField(db_column='total_odering', default=0),
        ),
    ]
