# Generated by Django 4.1.1 on 2022-09-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestore', '0007_alter_cart_total_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_ordering',
            field=models.IntegerField(default=0),
        ),
    ]
