# Generated by Django 4.1.1 on 2022-09-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakestore', '0016_rename_cart_cartitem_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
