# Generated by Django 4.1.1 on 2022-09-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakestore', '0022_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
